plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '3.1.1'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.github.mkpaz:atlantafx-base:2.0.1'
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

application {
    // This connects to your App.java file
    mainClass = 'io.github.jaber.starter.App'
    applicationDefaultJvmArgs = ['-Dglass.gtk.uiScale=1.5']
}

jlink {
    moduleName = 'io.github.jaber.starter'
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    launcher {
        name = 'FXStarter'
    }
    jpackage {
        skipInstaller = true
        installerOptions = ['--description', 'JavaFX Starter App', '--copyright', '2025 Jaber']
    }
}
